const personagens = [
  {
    name: 'InuYasha',
    description: 'Half-demon and half-human, aparência de humano com traços caninos',
    attr1: 70,
    attr2: 60,
    attr3: 80,
    image: 'https://i.gifer.com/TBtW.gif',
    rarity: 'muito raro',
    trunfo: false,
  },
  {
    name: 'Kagome',
    description: 'Garota de 15 anos, reencarnação da Sacerdotisa Kikyou',
    attr1: 60,
    attr2: 20,
    attr3: 40,
    image: 'https://i.gifer.com/79iJ.gif',
    rarity: 'normal',
    trunfo: false,
  },
  {
    name: 'Sesshoumaru',
    description: 'Meio irmão mais velho de Inuyasha, e odeia os humanos',
    attr1: 80,
    attr2: 60,
    attr3: 70,
    image: 'https://i.gifer.com/1fbg.gif',
    rarity: 'raro',
    trunfo: false,
  },
  {
    name: 'Kikyou',
    description: 'Sacerdotisa encarregada de vigiar a Jóia de Quatro Almas',
    attr1: 70,
    attr2: 40,
    attr3: 50,
    image: 'https://i.gifer.com/C9FZ.gif',
    rarity: 'muito raro',
    trunfo: true,
  },
  {
    name: 'Shippo',
    description: 'Youkai-raposa criança, salvo por Inuyasha',
    attr1: 20,
    attr2: 40,
    attr3: 60,
    image: 'https://i.gifer.com/1AHe.gif',
    rarity: 'normal',
    trunfo: false,
  },
  {
    name: 'Kaede',
    description: 'Sacerdotisa gentil, irmã mais nova de Kikyou',
    attr1: 50,
    attr2: 30,
    attr3: 20,
    image: 'https://i.gifer.com/ADKU.gif',
    rarity: 'normal',
    trunfo: false,
  },
];

export default personagens;
